import { int, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { deletedAt, id, timestamps } from "./common-fields";

export const members = sqliteTable("members", {
  id: id(),
  full_name: text("full_name").notNull(),
  sex: text("sex"),
  mother: text("mother"),
  father: text("father"),
  birth_date: text("birth_date"),
  birth_place: text("birth_place"),
  marital_status: text("marital_status"),
  wedding_date: text("wedding_date"),
  spouse: text("spouse"),
  phone: text("phone"),
  email: text("email"),
  address_street: text("address_street"),
  address_number: text("address_number"),
  address_complement: text("address_complement"),
  nationality: text("nationality"),
  education: text("education"),
  profession: text("profession"),
  home_church: text("home_church"),
  baptism_year: int("baptism_year"),
  baptism_place: text("baptism_place"),
  prof_faith_year: int("prof_faith_year"),
  prof_faith_place: text("prof_faith_place"),
  member_since: text("member_since"),
  member_until: text("member_until"),
  status: text("status", {
    enum: ["active", "transferred", "deceased", "removed"],
  }).notNull(),
  ...timestamps(),
  ...deletedAt(),
});
